version: "3"

services:
  app:
    container_name: cake-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/var/www/html
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    ports:
      - 8000:80
    # command: /bin/bash /var/www/html/docker/setup.sh
    depends_on:
      - db

  db:
    container_name: cake-db
    image: mysql:5
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: cakephp_db
      MYSQL_ROOT_PASSWORD: root_password

volumes:
  db-data:
    external: false
